export const EVENT_ADD_REQUEST = 'EVENT_ADD_REQUEST'
export const EVENT_ADD_SUCCESS = 'EVENT_ADD_SUCCESS'
export const EVENT_ADD_FAIL = 'EVENT_ADD_FAIL'

export const EVENT_SORT_REQUEST = 'EVENT_SORT_REQUEST'
export const EVENT_SORT_SUCCESS = 'EVENT_SORT_SUCCESS'
export const EVENT_SORT_FAIL = 'EVENT_SORT_FAIL'

export const EVENT_TYPECAT_REQUEST = 'EVENT_TYPECAT_REQUEST'
export const EVENT_TYPECAT_SUCCESS = 'EVENT_TYPECAT_SUCCESS'
export const EVENT_TYPECAT_FAIL = 'EVENT_TYPECAT_FAIL'

export const EVENT_GET_REQUEST = 'EVENT_GET_REQUEST'
export const EVENT_GET_SUCCESS = 'EVENT_GET_SUCCESS'
export const EVENT_GET_FAIL = 'EVENT_GET_FAIL'