export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const USER_BOOKED_UPCOMING_REQUEST = 'USER_BOOKED_UPCOMING_REQUEST'
export const USER_BOOKED_UPCOMING_SUCCESS = 'USER_BOOKED_UPCOMING_SUCCESS'
export const USER_BOOKED_UPCOMING_FAIL = 'USER_BOOKED_UPCOMING_FAIL'

export const USER_BOOKED_COMPLETED_REQUEST = 'USER_BOOKED_COMPLETED_REQUEST'
export const USER_BOOKED_COMPLETED_SUCCESS = 'USER_BOOKED_COMPLETED_SUCCESS'
export const USER_BOOKED_COMPLETED_FAIL = 'USER_BOOKED_COMPLETED_FAIL'

export const USER_REGISTERED_UPCOMING_REQUEST = 'USER_REGISTERED_UPCOMING_REQUEST'
export const USER_REGISTERED_UPCOMING_SUCCESS = 'USER_REGISTERED_UPCOMING_SUCCESS'
export const USER_REGISTERED_UPCOMING_FAIL = 'USER_REGISTERED_UPCOMING_FAIL'

export const USER_REGISTERED_COMPLETED_REQUEST = 'USER_REGISTERED_COMPLETED_REQUEST'
export const USER_REGISTERED_COMPLETED_SUCCESS = 'USER_REGISTERED_COMPLETED_SUCCESS'
export const USER_REGISTERED_COMPLETED_FAIL = 'USER_REGISTERED_COMPLETED_FAIL'

export const USER_FAVOURITES_REQUEST = 'USER_FAVOURITES_REQUEST'
export const USER_FAVOURITES_SUCCESS = 'USER_FAVOURITES_SUCCESS'
export const USER_FAVOURITES_FAIL = 'USER_FAVOURITES_FAIL'

export const USER_LIKE_EVENT_REQUEST = 'USER_LIKE_EVENT_REQUEST'
export const USER_LIKE_EVENT_SUCCESS = 'USER_LIKE_EVENT_SUCCESS'
export const USER_LIKE_EVENT_FAIL = 'USER_LIKE_EVENT_FAIL'

export const USER_DISLIKE_EVENT_REQUEST = 'USER_DISLIKE_EVENT_REQUEST'
export const USER_DISLIKE_EVENT_SUCCESS = 'USER_DISLIKE_EVENT_SUCCESS'
export const USER_DISLIKE_EVENT_FAIL = 'USER_DISLIKE_EVENT_FAIL'

export const USER_BOOK_REQUEST = 'USER_BOOK_REQUEST'
export const USER_BOOK_SUCCESS = 'USER_BOOK_SUCCESS'
export const USER_BOOK_FAIL = 'USER_BOOK_FAIL'

export const USER_REVIEW_REQUEST = 'USER_REVIEW_REQUEST'
export const USER_REVIEW_SUCCESS = 'USER_REVIEW_SUCCESS'
export const USER_REVIEW_FAIL = 'USER_REVIEW_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'